### ISSUE TITLE
Should Paper Now article functions & styles be update-able from this template repo?

### ISSUE THREAD

**Issue by katrinleinweber** [PeerJ/paper-now#31]
As long as authors have only one article, authors can of course leave it be a normal fork and merge new template features via GitHub's GUI. But once they/we start the next article, and one after that...? Should each one try `git subtree` ([apparently](http://stackoverflow.com/a/14992078)) or we ask GitHub for some official way to fork a repo multiple times?

Or should Paper Now instances not be updated? If so, for what reasons? Looking forward to your opinions :-)

**Comment by hubgit** [comment]
For the first point, see the current README - the recommendation is to use GitHub's importer (which is essentially cloning), rather than forking.

Longer term, I'd like to be able to generate a fresh repository for each article rather than cloning (see https://github.com/PeerJ/paper-now/issues/25).

For automatic updates to styles and scripts, I've been looking at various ways of using progressive enhancement to load those in from a separate repository, but haven't landed on a solution yet - it's a fine balance between making it easy to push updates and preserving the author's control of how the article looks and behaves.

**Comment by katrinleinweber** [comment]
It is. That's why I first assumed merging might be best. Looking forward to testing the automatic updates implementations when they are ready :-)

**Comment by hubgit** [comment]
The styles, scripts and column layout are now in a separate web component, so that they can be updated independently of the article content. 

This has upset some web browsers (mostly older ones, though MathJax is unhappy everywhere except Chrome), but we can work around that.
