### ISSUE TITLE
Document wide TeX macros

### ISSUE THREAD

**Issue by j2kun** [PeerJ/paper-now#46]
Mathematicians who want to write papers often make document wide macros to abbreviate common math forms. For example, in theoretical computer science we like to have lots of upper-case complexity class names, leading to macros like

```
\newcommand{\SPACE}{\textup{SPACE}} 
```

So we can write `$\SPACE(n^2)$` anywhere in our paper.

I'd like to request this feature in Paper Now. I think it will attract more mathematicians to this publication medium.

**Comment by hubgit** [comment]
The [MathJax documentation](http://docs.mathjax.org/en/latest/extension-writing.html#extension-to-define-tex-macros) has some information about defining TeX macros. Hopefully it should be possible to add that configuration at the start of the page so that the macros are available throughout the document.

**Comment by j2kun** [comment]
I'd love to see a minimal working example.
